name: panda3
channels:
  - pytorch
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py310h5764c6d_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - biopython=1.79=py310h6acc77f_1
  - biotite=0.34.1=py310h5764c6d_1
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.5=pyhd8ed1ab_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - cd-hit=4.8.1=h5b5514e_6
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - flatbuffers=2.0.6=h27087fc_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.3.3=py310h5764c6d_0
  - gast=0.5.3=pyhd8ed1ab_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - git=2.34.1=pl5262hc120c5b_0
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.15.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.46.1=h33aed49_0
  - grpcio=1.46.1=py310h44b9e0c_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=3.7.0=nompi_py310h06dffec_100
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py310h06a4308_0
  - ipython=8.3.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.4.0=py310h06a4308_0
  - jupyter=1.0.0=py310h06a4308_7
  - jupyter_client=7.2.2=py310h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras=2.8.0=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py310h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h6239696_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.5.1=py310h06a4308_1
  - matplotlib-base=3.5.1=py310ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py310h7f8727e_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - msgpack-python=1.0.3=py310hd09550d_0
  - multidict=6.0.2=py310h5764c6d_2
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.4.4=py310h06a4308_0
  - nbformat=5.3.0=py310h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - notebook=6.4.11=py310h06a4308_0
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h0b41bf4_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py310h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.26.2=h14c3975_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310hace64e9_1
  - pip=21.2.4=py310h06a4308_0
  - prettytable=3.4.0=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.20.1=py310hd8f1fbe_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py310h295c915_6
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-flatbuffers=22.12.6=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.0=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py310h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.3.0=py310h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py310h06a4308_0
  - sip=4.19.13=py310h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=hbd366e4_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py310h597c629_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.8.2=mkl_py310hd2b8f8c_0
  - tensorflow-base=2.8.2=mkl_py310hf890080_0
  - tensorflow-estimator=2.8.0=py310h2f386ee_0
  - termcolor=2.1.1=pyhd8ed1ab_0
  - terminado=0.13.1=py310h06a4308_0
  - testpath=0.6.0=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.0=py310_cu113
  - torchvision=0.13.0=py310_cu113
  - tornado=6.1=py310h7f8727e_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py310h06a4308_0
  - wrapt=1.14.1=py310h5764c6d_1
  - xz=5.2.5=h7f8727e_1
  - yarl=1.8.1=py310h5764c6d_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - fair-esm==1.0.2
    - py3dmol==1.8.1
    - scikit-learn==1.1.1
    - scipy==1.9.0
    - threadpoolctl==3.1.0
    - torch-geometric==2.0.4
    - torch-scatter==2.0.9
    - torch-sparse==0.6.14
    - tqdm==4.64.0
prefix: /home/czhao/anaconda3/envs/panda3
